name: "Deploy to FaableCloud"
author: "FaableCloud"
description: "Deploy a node app to heroku"
branding:
  icon: "upload-cloud"
  color: "purple"
inputs:
  faable_app_name:
    description: "Faablecloud app name"
    required: true
  faable_user:
    description: "Faablecloud user name"
    required: true
  faable_api_key:
    description: "faable deployment apikey"
    required: true
  enable_debug:
    description: "enable build debug"
    required: false
  npm_build_command:
    description: "which command to build the package.json (default: build)"
    required: false
  npm_start_command:
    description: "which command to start the deployment (default: start)"
    required: false
outputs:
  status:
    description: "The Success/Failure of the action"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: "14"
    - run: yarn install --frozen-lockfile
      shell: bash
    - run: node deploy/index.js
      shell: bash
