name: "Deploy to FaableCloud"
description: "Deploy a node app to heroku"
branding:
  icon: "upload-cloud"
  color: "purple"
inputs:
  faable_app_name:
    description: "Faablecloud app name"
    required: true
  faable_api_key:
    description: "faable deployment apikey"
    required: true
outputs:
  status:
    description: "The Success/Failure of the action"
runs:
  using: "node12"
  main: "dist/deploy.js"
