name: "Deploy to FaableCloud"
description: "Deploy a node app to heroku"
branding:
  icon: "upload-cloud"
  color: "purple"
inputs:
  faable_api_key:
    description: "This will be used for authentication. You can find it in your heroku homepage account settings"
    required: true
  faable_email:
    description: "Email that you use with heroku"
    required: true
  faable_app_name:
    description: "The appname to use for deploying/updating"
    required: true
  branch:
    description: "The branch that you would like to deploy to Heroku"
    default: "HEAD"
    required: false
  usedocker:
    description: "Will deploy using Dockerfile in project root."
    default: "false"
    required: false
outputs:
  status:
    description: "The Success/Failure of the action"
runs:
  using: "node12"
  main: "dist/deploy.js"
