name: Release
on:
  push:
    branches:
      - "*"
jobs:
  build:
    name: build-package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - run: yarn install --frozen-lockfile
      - run: yarn run build
