name: Release
on:
  push:
    branches: [main]
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - run: yarn install --frozen-lockfile
      - run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.GH_TOKEN }}
      - uses: ./
        with:
          faable_app_name: "test"
          faable_api_key: ${{ secrets.FAABLE_API_KEY }}
          faable_user: "faable"
