name: Release
on:
  push:
    branches:
      - "*"
jobs:
  autotest:
    name: autotest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          faable_app_name: "test"
          faable_api_key: 1234
          faable_user: "faable"
