name: Tests

on:
  push:
    branches: [main]

jobs:
  deploy-test-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm run setup tests/test-1/data.json
      - uses: faabledata/action-deploy@master
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "akhileshns-hd-test-1"
          heroku_email: "nsakhilesh02@gmail.com"
          appdir: "tests/test-1"
      
