name: Tests

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
          with:
            node-version: "12.x"
        - run: yarn install --frozen-lockfile
        - run: yarn release
          env:
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
            NPM_TOKEN: ${{ secrets.GH_TOKEN }}
