name: Tests

on:
  push:
    branches: [main]

jobs:
  deploy-test-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: faablecloud/action-deploy@main
        with:
          faable_app_name: "test-123"
          faable_user: "tailorhub"
          enable_debug: true
      env:
          FAABLE_API_KEY: ${{ secrets.FAABLE_API_KEY }}

