name: Tests

on:
  push:
    branches: [main]

jobs:
  deploy-test-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: faablecloud/action-deploy@main
        with:
          faable_app_name: "faable-test"
          faable_api_key: ${{ secrets.FAABLE_API_KEY }}
          faable_user: "faable"
          enable_debug: true
